[package]
name = "gametoy"
version = "0.1.0"
authors = ["Geoffrey Irons <sdfgeoff@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
glow = "0.10.0"
tar = "0.4"
serde_json = "1.0.59"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.0"
png = "0.16.8"

